#ifndef CONFIG_H
#define CONFIG_H

#define NUM_PHOTONS 1000
#define SCENE_1_NUM_CAUSTIC_PHOTONS 10000
#define SCENE_2_NUM_CAUSTIC_PHOTONS 2000000

#define ICACHE_TOLERANCE 1
#define ICACHE_MIN_SPACING 1
#define ICACHE_MAX_SPACING_RATIO 100

#define MONTE_CARLO_STRATIFICATION_N 28;
#define MONTE_CARLO_STRATIFICATION_M 13;

#define CAUSTICS_SOFT_MAX_DISTANCE 4
#define CAUSTIC_SOFT_MAX_PHOTONS 1000
#define CAUSTICS_MAX_DISTANCE 1.1
#define CAUSTIC_MAX_PHOTONS 1000

#define INDIRECT_MAX_DISTANCE 30
#define INDIRECT_MAX_PHOTONS 200

#define NUM_SOFT_SHADOW_RAYS_IN_EACH_DIM 6

#define NUM_TRIAGLES_IN_EACH_DIM 499

#define EPSILON 0.001

#endif
